# Generated by Django 4.2.7 on 2023-11-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.article')),
            ],
        ),
    ]
