# Generated by Django 4.2.7 on 2023-11-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_photo_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='new_photo',
            field=models.ImageField(default='', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
