# Generated by Django 4.2.7 on 2023-11-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo_new_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='new_photo',
        ),
    ]
