# Generated by Django 4.2.7 on 2023-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_photo_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('Advice, Digital, Social Media', 'Advice, Digital, Social Media'), ('Advice, Lifestyle', 'Advice, Lifestyle'), ('Arts and Culture', 'Arts and Culture'), ('Beauty and Skincare', 'Beauty and Skincare'), ('Books', 'Books'), ('Education and Learning', 'Education and Learning'), ('Fashion', 'Fashion'), ('Fitness and Exercise', 'Fitness and Exercise'), ('Food', 'Food'), ('Interior Design', 'Interior Design'), ('Mindfulness', 'Mindfulness'), ('Movies', 'Movies'), ('Music', 'Music'), ('Nutrition', 'Nutrition'), ('Phycology, Advice', 'Phycology, Advice'), ('Photography', 'Photography'), ('Recipes', 'Recipes'), ('Stories', 'Stories'), ('Travel', 'Travel')], default='Advice, Lifestyle', max_length=50),
        ),
    ]
